Repository razeware/emitron-Android, pull requests merged in 2021-03, with the labels that each got.

#327 Moved Settings to its own tab.
  app/src/main/java/com/razeware/emitron/MainActivity.kt
  app/src/main/java/com/razeware/emitron/ui/mytutorial/MyTutorialFragment.kt
  app/src/main/java/com/razeware/emitron/ui/settings/SettingsBottomSheetDialogFragment.kt
  app/src/main/java/com/razeware/emitron/ui/settings/SettingsFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_tutorials.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/emitron_navigation.xml
  app/src/main/res/navigation/settings_navigation.xml
Labels: enhancement

#323 EMA-312- Fix completed badge color
  app/src/main/res/layout/fragment_collection.xml
  app/src/main/res/layout/item_content.xml
  styles/src/main/res/drawable/bg_overline_raised_success.xml
  styles/src/main/res/values-v28/styles.xml
  styles/src/main/res/values-v29/styles.xml
  styles/src/main/res/values/colors.xml
  styles/src/main/res/values/styles.xml
Labels: bug

#325 Added checks to see if there is an Activity to handle the intent
  inappreview/src/main/java/com/raywenderlich/android/inappreview/manager/InAppReviewManagerImpl.kt
Labels: bug, enhancement, fixed

#329 EMA-328 - Added flags to enable contributors to use the app
  CONTRIBUTING.md
  README.md
  app/src/main/java/com/razeware/emitron/MainViewModel.kt
  app/src/main/java/com/razeware/emitron/data/login/LoginPrefs.kt
  app/src/main/java/com/razeware/emitron/data/login/LoginRepository.kt
  app/src/main/java/com/razeware/emitron/ui/collection/CollectionFragment.kt
  app/src/main/java/com/razeware/emitron/ui/collection/CollectionViewModel.kt
  app/src/main/java/com/razeware/emitron/ui/login/PermissionActionDelegate.kt
  app/src/main/res/layout/fragment_collection.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/razeware/emitron/MainViewModelTest.kt
  app/src/test/java/com/razeware/emitron/ui/login/PermissionActionDelegateTest.kt
Labels: documentation, enhancement

#326 EMA-316 - Removed the pro course body text
  app/src/main/java/com/razeware/emitron/ui/collection/CollectionFragment.kt
  app/src/main/res/layout/fragment_collection.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
